# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ed0_ <- function(yday, hour, lat, lon, tcl, o3, cf, albedo, filename) {
    .Call(`_ed0_ed0_`, yday, hour, lat, lon, tcl, o3, cf, albedo, filename)
}

edpar_ <- function(yday, hour, lat, lon, tcl, o3, cf, albedo, filename) {
    .Call(`_ed0_edpar_`, yday, hour, lat, lon, tcl, o3, cf, albedo, filename)
}

